### ISSUE TITLE
Open www.dumpert.nl/* urls in DR

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#26] opened 2016-01-07 15:02 UTC
At the moment, DR cannot directly open urls that start with www.dumpert.nl. 

! [Imgur](http://i.imgur.com/sZIuPYo.jpg)

It would be nice if it could.

**Comment by CytoDev** [comment] 2016-01-07 15:04
Agreed. Easily implemented, but hard to filter out as far as I can see. There needs to be a single entry point for all items...  
  
Another thing to note is that those links you see floating around in the comments literally link to what they say. Full urls are not followed.

**Comment by CytoDev** [comment] 2016-01-10 13:11
As of [#6ba2bab](https://github.com/jariz/Dumpert/commit/6ba2bab431e0a6f4d6bf3c9cab461fb8706e3824) links will be parsed correctly and move to the right page in the domain. Catching pages from Dumpert to the application is something I am hesitant about since that would infringe more on Geenstijl's rights.

**Comment by GijsTimmers** [comment] 2016-01-11 19:56
So links from Dumpert to Dumpert work?

**Comment by CytoDev** [comment] 2016-01-12 06:25
They open in the browser, yes. The issue is that links are opened the way they are displayed. This means that if a comment reads "blah dumpert.nl... blah" they would link to the top domain, and not to whatever the actual anchor tag links to. It was resolved by parsing the anchor tag as html and putting that in the TextView. However, since I implemented the clicking on comments to vote/reply the functionality is broken again. I will take a look at it later today.

**Comment by GijsTimmers** [comment] 2016-01-12 07:24
OK, sounds appealing!

**Comment by CytoDev** [comment] 2016-01-12 07:55
It didn't break when I implemented the clicking on items to expand the interaction layout, it seems to have been broken by adding `android:autoLink="web"` to the TextView. I fixed it by setting the linking to `none`. Links are parsed as HTML anyway.

**Comment by jariz** [comment] 2016-01-13 10:56
@CytoDev we're a 'for Dumpert.nl' app, we should open Dumpert.nl links.
Couldn't care less about GeenStijl, as long as the project stays legal (aka them having no grounds to sue me, lol.)

**Comment by CytoDev** [comment] 2016-01-13 11:12
In that case we will need to parse the media base URLs. I believe this is unsupported at this time. Will look into it when #43 is resolved.

**Closed** 2016-01-13 13:18 UTC
Labels: feature request
