### ISSUE TITLE
Official dumpert app recreated from scratch

### ISSUE THREAD

**Issue by KeizerDev** [jariz/Dumpert#62] opened 2016-01-19 15:07 UTC
![screenshot_2016-01-19-16-04-36](https://cloud.githubusercontent.com/assets/4026917/12422311/9dfe92d2-bec6-11e5-8867-bf65ed247d6c.png)
![screenshot_2016-01-19-16-04-21](https://cloud.githubusercontent.com/assets/4026917/12422331/c2528e86-bec6-11e5-9d15-00cad3b0ede7.png)

**Comment by jariz** [comment] 2016-01-19 15:11
Yes, was aware they were working on this. Congrats to them. Ours will stay online as an open source alternative.
Maybe it uses a real API which we could reverse engineer so we can finally ditch scraping? :stuck_out_tongue: 
Can anyone try to figure that out?

also
>alleen het reageren in de app is technisch was lastig

hahah
@CytoDev apply for a job :stuck_out_tongue:

**Comment by CytoDev** [comment] 2016-01-19 15:15
Whahahahah commenting was the easy part! XD

**Comment by CytoDev** [comment] 2016-01-19 15:19
@jariz I'll take a look at reverse engineering it later this week. Got some tools lying around for just that. ;)

**Comment by KeizerDev** [comment] 2016-01-19 15:37
@CytoDev Me too! I can do it tonight if you want :wink:

**Comment by jariz** [comment] 2016-01-19 15:59
Friend of mine quickly took a look and I can confirm that *it uses a real API!*, all programmers rejoice! :tada: 

![](https://i.imgur.com/pCGdmvf.png)

**Comment by KeizerDev** [comment] 2016-01-19 16:30
@jariz Wow, good catch! I will look into it a bit further now. Maybe I can see some more interesting stuff!

**Comment by KeizerDev** [comment] 2016-01-19 16:33
`http://dumpcomments.geenstijl.nl/api/{items.id}`

**Comment by KeizerDev** [comment] 2016-01-19 16:35
Thank god, they use retrofit.
```
URL: http://www.dumpert.nl/mobile_api/json/

public abstract interface APIRequests
{
  @GET("/classics/{page}")
  public abstract void classicItems(@Path("page") int paramInt, Callback<MainResponse> paramCallback);
  
  @GET("/foto/toppers/{page}")
  public abstract void classicPhotoItems(@Path("page") int paramInt, Callback<MainResponse> paramCallback);
  
  @GET("/video/toppers/{page}")
  public abstract void classicVideoItems(@Path("page") int paramInt, Callback<MainResponse> paramCallback);
  
  @GET("/{id}")
  public abstract void commentItems(@Path("id") String paramString, Callback<CommentResponse> paramCallback);
  
  @GET("/rating/{id}")
  public abstract void commentRatings(@Path("id") String paramString, Callback<CommentRatings> paramCallback);
  
  @GET("/top5/dag/{date}")
  public abstract void dayItems(@Path("date") String paramString, Callback<MainResponse> paramCallback);
  
  @GET("/info/{id}")
  public abstract void getItemInfo(@Path("id") String paramString, Callback<MainResponse> paramCallback);
  
  @GET("/hotshiz")
  public abstract void hotItem(Callback<MainResponse> paramCallback);
  
  @GET("/latest/{page}")
  public abstract void latestItems(@Path("page") int paramInt, Callback<MainResponse> paramCallback);
  
  @GET("/top5/maand/{date}")
  public abstract void monthItems(@Path("date") String paramString, Callback<MainResponse> paramCallback);
  
  @GET("/foto/latest/{page}")
  public abstract void photoItems(@Path("page") int paramInt, Callback<MainResponse> paramCallback);
  
  @GET("/ratecomment/{itemId}/{id}/{action}")
  public abstract void rateCommentItem(@Path("itemId") String paramString1, @Path("id") String paramString2, @Path("action") String paramString3, Callback<RatingResponse> paramCallback);
  
  @GET("/rating/{id}/{action}")
  public abstract void rateItem(@Path("id") String paramString1, @Path("action") String paramString2, Callback<RatingResponse> paramCallback);
  
  @GET("/related/{id}")
  public abstract void relatedItems(@Path("id") String paramString, Callback<MainResponse> paramCallback);
  
  @GET("/search/{term}/{page}")
  public abstract void searchItems(@Path("term") String paramString, @Path("page") int paramInt, Callback<MainResponse> paramCallback);
  
  @GET("/feed/174")
  public abstract void sponsoredItems(Callback<AdItem> paramCallback);
  
  @GET("/{mediatype}/top5/{datetype}/{date}")
  public abstract void topItems(@Path("mediatype") String paramString1, @Path("datetype") String paramString2, @Path("date") String paramString3, Callback<MainResponse> paramCallback);
  
  @POST("/upload/index2.php?JSON")
  public abstract void upload(@Body MultipartTypedOutput paramMultipartTypedOutput, Callback<UploadItem> paramCallback);
  
  @GET("/video/latest/{page}")
  public abstract void videoItems(@Path("page") int paramInt, Callback<MainResponse> paramCallback);
  
  @GET("/viewed/{id}")
  public abstract void viewedItem(@Path("id") String paramString, Callback<ViewedResponse> paramCallback);
  
  @GET("/top5/week/{date}")
  public abstract void weekItems(@Path("date") String paramString, Callback<MainResponse> paramCallback);
}
```

**Comment by KeizerDev** [comment] 2016-01-19 16:38
I have some experience with retrofit, so if there are any questions about the parameters(I don't think so) I can help.

**Comment by CytoDev** [comment] 2016-01-19 16:42
We already knew the whole dumpcomments thing didn't we?

**Comment by KeizerDev** [comment] 2016-01-19 16:46
I wasn't aware of that. But yeah, I just posted the stuff I founded

**Comment by jariz** [comment] 2016-01-20 10:31
Gonna close this issue now because #64 has sprouted from this discussion.

**Closed by jariz** 2016-01-20 10:31 UTC
Labels: discussion
