### ISSUE TITLE
App reloads when playing in fullscreen mode

### ISSUE THREAD

**Issue by KeizerDev** [jariz/Dumpert#10] opened 2015-12-10 08:49 UTC
Fullscreen mode doesn't work in build #8 on One Plus X (@CytoDev)

**Comment by CytoDev** [comment] 2015-12-10 08:54
Any logs?

**Comment by KeizerDev** [comment] 2015-12-10 09:30
```

12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime: FATAL EXCEPTION: main
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime: Process: io.jari.dumpert, PID: 25801
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.jari.dumpert/io.jari.dumpert.activities.VideoActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2362)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:155)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:139)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5308)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:  Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false }
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:422)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at io.jari.dumpert.activities.VideoActivity.onCreate(VideoActivity.java:43)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6072)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424) 
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:155) 
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323) 
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:139) 
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5308) 
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
12-10 10:30:12.633 25801-25801/io.jari.dumpert E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
```

**Comment by KeizerDev** [comment] 2015-12-10 09:31
Yeah, wait. The videoplayer now sucks for me. Let's use https://github.com/xiongwei-git/AndroidVideoPlayer

**Comment by CytoDev** [comment] 2015-12-10 09:39
Great... I just fixed it...

**Comment by KeizerDev** [comment] 2015-12-10 10:01
Yeah, I was actually planning to just move it to another player and make it more dependency based.
For example the drawer, can be like https://github.com/mikepenz/MaterialDrawer and we can use https://github.com/jtribe/shelly for intents

**Comment by CytoDev** [comment] 2015-12-10 10:26
The reloading problem should have been fixed with [#5791190](https://github.com/CytoDev/Dumpert/commit/57911902647740e6da1acd3ab57c6229af3ba1ac), but videoView resolves to null. Which is probably a stupid error on my part though.

**Comment by KeizerDev** [comment] 2015-12-10 11:50
@CytoDev Let's just move it to the other videoplayer I mentioned above, it will handle all the stuff that's needed to be and will keep the code clean. I'll implemented it now if you agree with it.

**Comment by CytoDev** [comment] 2015-12-10 12:02
Take a look at my last commit and decide if it is really necessary. The video player is finally working as intended, and issue #9 should be a breeze to implement now. Still, the other player looks really nice. But wouldn't it be overkill for such a simple feature? Most of the videos on Dumpert aren't even _that_ high definition.

**Comment by jariz** [comment] 2015-12-10 12:05
The only real advantage I'm seeing in that other player is the quality switch, which can already be done through the preferences of the app. Seems like way too much of an hassle, especially if this reloading video issue is fixed now.

**Comment by KeizerDev** [comment] 2015-12-10 12:09
I see some more advantage. 
Like now, when I'm starting the video and decide to switch to fullscreen halfway the video it needs to be buffered again and starts over. 
Further, when the video is buffering and I lock my phone it just plays while my phone is off.

**Closed** 2015-12-10 12:16 UTC
