### ISSUE TITLE
Weird layout issue on some posts

### ISSUE THREAD

**Issue by ghost** [jariz/Dumpert#2] opened 2015-07-06 10:59 UTC
On some posts (and this happens randomly) the layout holding the comments is pushed down and seems to overlap randomly.

screenshot from a Samsung Galaxy Core Prime LTE (SM-G360F) Android version 5.0.2 (Polish release from 2015-05-11)
![screenshot_2015-07-04-17-05-31](https://cloud.githubusercontent.com/assets/11539737/8520827/4fc9d7c6-23de-11e5-9792-c43b4ed9d1af.png)

**Comment by CytoDev** [comment] 2015-12-09 10:24
My account is migrated over to this one. This is still an issue on some posts. The weird thing is that it is not reproducible when in a debug build.

**Comment by CytoDev** [comment] 2015-12-10 12:08
This issue has not happened since [#930b820](https://github.com/CytoDev/Dumpert/commit/930b8201e2b33cff325d3fdc8a2a51cb3a34b9cf). Close the issue, @jariz?

**Closed** 2015-12-10 12:19 UTC
